apiVersion: apps/v1
kind: Deployment
metadata:
  name: ubuntu-deployment
  labels:
    app: ubuntu
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ubuntu
  template:
    metadata:
      labels:
        app: ubuntu
    spec:
      containers:
      - name: ubuntu
        image: ubuntu
        command: ["sh", "-c", "echo 'Container started'; sleep infinity"]
        volumeMounts:
          - name: script-volume
            mountPath: /install-tools
            readOnly: true
          - name: aws-env-volume
            mountPath: /aws-vars
            readOnly: true
          - name: hlf-volume
            mountPath: /install-hlf
            readOnly: true
      volumes:
        - name: script-volume
          configMap:
            name: install-tools
        - name: aws-env-volume
          secret:
            secretName: aws-env
        - name: hlf-volume
          configMap:
            name: install-hlf
