apiVersion: apps/v1
kind: Deployment
metadata:
  name: hlf-toolbox-deployment
  labels:
    app: hlf-toolbox
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hlf-toolbox
  template:
    metadata:
      labels:
        app: hlf-toolbox
    spec:
      containers:
      - name: hlf-toolbox
        image: rafaelluna2410/hlf-toolbox
        command: ["sh", "-c", "echo 'Container started'; sleep infinity"]
        envFrom:
        - secretRef:
            name: config-hlf-env
        volumeMounts:
          - name: script-volume
            mountPath: /install-tools
          - name: aws-env-volume
            mountPath: /aws-vars
          - name: hlf-volume
            mountPath: /install-hlf
      volumes:
        - name: script-volume
          configMap:
            name: install-tools
        - name: aws-env-volume
          secret:
            secretName: aws-env
        - name: hlf-volume
          configMap:
            name: install-hlf
