apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: hlf-toolbox-deployment
  labels:
    app: hlf-toolbox
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hlf-toolbox
  template:
    metadata:
      labels:
        app: hlf-toolbox
    spec:
      containers:
      - name: hlf-toolbox
        image: rafaelluna2410/hlf-toolbox
        command: ["sh", "-c", "/install-hlf/istio-coredns.sh; /install-hlf/hlf-auto.sh; sleep infinity"]
        #command: ["sh", "-c", "/install-hlf/hlf-auto.sh; sleep infinity"]
        envFrom:
        - secretRef:
              name: config-hlf-env
        volumeMounts:
          - name: hlf-volume
            mountPath: /install-hlf
      volumes:
        - name: hlf-volume
          configMap:
            name: install-hlf
            defaultMode: 0755
